/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caculator;

/**
 *
 * @author Nimantha Madushanka
 */
public class Calculator extends javax.swing.JFrame {

    double first_num;
    double second_num;
    double result;
    String oper;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        sev = new javax.swing.JButton();
        eig = new javax.swing.JButton();
        nin = new javax.swing.JButton();
        min = new javax.swing.JButton();
        fou = new javax.swing.JButton();
        fev = new javax.swing.JButton();
        six = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        thre = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        div = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        equl = new javax.swing.JButton();
        point = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        display2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        display.setBackground(new java.awt.Color(0, 0, 0));
        display.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        display.setAlignmentX(0.7F);
        display.setAlignmentY(0.7F);
        display.setBorder(null);
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayKeyTyped(evt);
            }
        });

        sev.setBackground(new java.awt.Color(204, 204, 204));
        sev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sev.setText("7");
        sev.setFocusPainted(false);
        sev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sevMouseReleased(evt);
            }
        });
        sev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevActionPerformed(evt);
            }
        });
        sev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sevKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sevKeyReleased(evt);
            }
        });

        eig.setBackground(new java.awt.Color(204, 204, 204));
        eig.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eig.setText("8");
        eig.setFocusPainted(false);
        eig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eigMouseReleased(evt);
            }
        });
        eig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eigActionPerformed(evt);
            }
        });

        nin.setBackground(new java.awt.Color(204, 204, 204));
        nin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nin.setText("9");
        nin.setFocusPainted(false);
        nin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ninMouseReleased(evt);
            }
        });
        nin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninActionPerformed(evt);
            }
        });

        min.setBackground(new java.awt.Color(255, 51, 0));
        min.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setText("-");
        min.setFocusPainted(false);
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minMouseReleased(evt);
            }
        });
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });

        fou.setBackground(new java.awt.Color(204, 204, 204));
        fou.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fou.setText("4");
        fou.setFocusPainted(false);
        fou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fouMouseReleased(evt);
            }
        });
        fou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fouActionPerformed(evt);
            }
        });

        fev.setBackground(new java.awt.Color(204, 204, 204));
        fev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fev.setText("5");
        fev.setFocusPainted(false);
        fev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fevMouseReleased(evt);
            }
        });
        fev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fevActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(204, 204, 204));
        six.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        six.setText("6");
        six.setFocusPainted(false);
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sixMouseReleased(evt);
            }
        });
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(255, 51, 0));
        plus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.setFocusPainted(false);
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                plusMouseReleased(evt);
            }
        });
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        thre.setBackground(new java.awt.Color(204, 204, 204));
        thre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thre.setText("3");
        thre.setFocusPainted(false);
        thre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                threMouseReleased(evt);
            }
        });
        thre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(204, 204, 204));
        one.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        one.setText("1");
        one.setFocusPainted(false);
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oneMouseReleased(evt);
            }
        });
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(204, 204, 204));
        two.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        two.setText("2");
        two.setFocusPainted(false);
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                twoMouseReleased(evt);
            }
        });
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(255, 51, 0));
        div.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("/");
        div.setFocusPainted(false);
        div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divMouseReleased(evt);
            }
        });
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(204, 204, 204));
        zero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zero.setText("0");
        zero.setFocusPainted(false);
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                zeroMouseReleased(evt);
            }
        });
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        mul.setBackground(new java.awt.Color(255, 51, 0));
        mul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mul.setForeground(new java.awt.Color(255, 255, 255));
        mul.setText("X");
        mul.setFocusPainted(false);
        mul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mulMouseReleased(evt);
            }
        });
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        equl.setBackground(new java.awt.Color(0, 204, 153));
        equl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        equl.setText("=");
        equl.setFocusPainted(false);
        equl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                equlMouseReleased(evt);
            }
        });
        equl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equlActionPerformed(evt);
            }
        });

        point.setBackground(new java.awt.Color(204, 204, 204));
        point.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        point.setText(".");
        point.setFocusPainted(false);
        point.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pointMouseReleased(evt);
            }
        });
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("C");
        clear.setFocusPainted(false);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clearMouseReleased(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        display2.setBackground(new java.awt.Color(153, 153, 153));
        display2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        display2.setBorder(javax.swing.BorderFactory.createTitledBorder("Equation"));
        display2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fou, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fev, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(point, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sev, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eig, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(display2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(display2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sev, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eig, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fou, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fev, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + two.getText();
        display.setText(c);
    }//GEN-LAST:event_twoActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void equlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equlActionPerformed
        // TODO add your handling code here:
        String answer;
        second_num = Double.parseDouble(display.getText());
        if (oper == "-") {
            result = first_num - second_num;
            String c = "";
            display.setText(c+result);
        } else if (oper == "+") {
            result = first_num + second_num;
            String c = "";
            display.setText(c+result);
        } else if (oper == "x") {
            result = first_num * second_num;
            String c = "";
            display.setText(c+result);
        } else if (oper == "/") {
            result = first_num / second_num;
            String c = "";
            display.setText(c+result);
        }
    }//GEN-LAST:event_equlActionPerformed

    private void sevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + sev.getText();
        display.setText(c);
    }//GEN-LAST:event_sevActionPerformed

    private void eigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eigActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + eig.getText();
        display.setText(c);
    }//GEN-LAST:event_eigActionPerformed

    private void ninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + nin.getText();
        display.setText(c);
    }//GEN-LAST:event_ninActionPerformed

    private void fouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fouActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + fou.getText();
        display.setText(c);
    }//GEN-LAST:event_fouActionPerformed

    private void fevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fevActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + fev.getText();
        display.setText(c);
    }//GEN-LAST:event_fevActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + six.getText();
        display.setText(c);
    }//GEN-LAST:event_sixActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + one.getText();
        display.setText(c);
    }//GEN-LAST:event_oneActionPerformed

    private void threActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + thre.getText();
        display.setText(c);
    }//GEN-LAST:event_threActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + zero.getText();
        display.setText(c);
    }//GEN-LAST:event_zeroActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        // TODO add your handling code here:
        String c = display.getText() + point.getText();
        display.setText(c);
    }//GEN-LAST:event_pointActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
        first_num = Double.parseDouble(display.getText());
        display.setText("");
        oper = "-";
    }//GEN-LAST:event_minActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        first_num = Double.parseDouble(display.getText());
        display.setText("");
        oper = "+";
    }//GEN-LAST:event_plusActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
        first_num = Double.parseDouble(display.getText());
        display.setText("");
        oper = "/";
    }//GEN-LAST:event_divActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        // TODO add your handling code here:
        first_num = Double.parseDouble(display.getText());
        display.setText("");
        oper = "x";
    }//GEN-LAST:event_mulActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        display.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void sevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sevKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_sevKeyReleased

    private void sevKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sevKeyPressed
        // TODO add your handling code here:
        display2.setText("7");
    }//GEN-LAST:event_sevKeyPressed

    private void displayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_displayKeyTyped

    private void display2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_display2ActionPerformed

    private void sevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + sev.getText();
        display2.setText(c);
    }//GEN-LAST:event_sevMouseReleased

    private void eigMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eigMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + eig.getText();
        display2.setText(c);
    }//GEN-LAST:event_eigMouseReleased

    private void ninMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ninMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + nin.getText();
        display2.setText(c);

    }//GEN-LAST:event_ninMouseReleased

    private void fouMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fouMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + fou.getText();
        display2.setText(c);
    }//GEN-LAST:event_fouMouseReleased

    private void fevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fevMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + fev.getText();
        display2.setText(c);
    }//GEN-LAST:event_fevMouseReleased

    private void sixMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + six.getText();
        display2.setText(c);
    }//GEN-LAST:event_sixMouseReleased

    private void oneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + one.getText();
        display2.setText(c);
    }//GEN-LAST:event_oneMouseReleased

    private void twoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + two.getText();
        display2.setText(c);
    }//GEN-LAST:event_twoMouseReleased

    private void threMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + thre.getText();
        display2.setText(c);
    }//GEN-LAST:event_threMouseReleased

    private void zeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + zero.getText();
        display2.setText(c);
    }//GEN-LAST:event_zeroMouseReleased

    private void pointMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + point.getText();
        display2.setText(c);
    }//GEN-LAST:event_pointMouseReleased

    private void equlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equlMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + equl.getText();
        display2.setText(c + result);
    }//GEN-LAST:event_equlMouseReleased

    private void minMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + min.getText();
        display2.setText(c);
    }//GEN-LAST:event_minMouseReleased

    private void plusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + plus.getText();
        display2.setText(c);
    }//GEN-LAST:event_plusMouseReleased

    private void divMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + div.getText();
        display2.setText(c);
    }//GEN-LAST:event_divMouseReleased

    private void mulMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulMouseReleased
        // TODO add your handling code here:
        String c = display2.getText() + mul.getText();
        display2.setText(c);
    }//GEN-LAST:event_mulMouseReleased

    private void clearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseReleased
        // TODO add your handling code here:
        display2.setText("");
    }//GEN-LAST:event_clearMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Calculator().setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Calculator().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTextField display;
    private javax.swing.JTextField display2;
    private javax.swing.JButton div;
    private javax.swing.JButton eig;
    private javax.swing.JButton equl;
    private javax.swing.JButton fev;
    private javax.swing.JButton fou;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton min;
    private javax.swing.JButton mul;
    private javax.swing.JButton nin;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JButton sev;
    private javax.swing.JButton six;
    private javax.swing.JButton thre;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
